const NOTIFICATION_TYPE = {
  ORDER_FILLED: "ORDER_FILLED",
  POSITION_CLOSED: "POSITION_CLOSED",
  POSITION_OPENED: "POSITION_OPENED",
};
const NOTIFICATION_TIMEOUT = 30000;

export { NOTIFICATION_TYPE, NOTIFICATION_TIMEOUT };
